### ISSUE TITLE
MTA build fails during JUnit test execution

### ISSUE THREAD

**Issue by alexanderparr** [SAP/devops-docker-images#53] opened 2019-03-28 21:01 UTC
Hi,
I like to use the official sap docker images to build our SCP App for neo. When doing so, I noticed that our mta build with some UI5 Apps and one java app fails while executing / starting JUnit tests with error message:

  -------------------------------------------------------
>   T E S T S
>  -------------------------------------------------------
>  Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Please have a look at our sample repository at:

Pipeline execution
https://bitbucket.org/p36/sap-mta-test/addon/pipelines/home#!/results/3

Source code repo, which contains the java code as maven project and the pipeline definition:
https://bitbucket.org/p36/sap-mta-test/src/master/

I can build the same repository on my local machine with different versions of the SAP MTA Builder.

Best
Alex

**Comment by fwilhe** [comment] 2019-04-05 15:03
Hi @alexanderparr,

sorry for the late reply.

This issue looks like an incompatibility between surefire and a newer maven version. Please update surefire in your tests to the latest version (`3.0.0-M3`), this should fix the issue.

Kind regards

Florian

**Comment by alexanderparr** [comment] 2019-04-05 18:00
Hi @fwilhe,
when I build the same app with docker image "maven:3.3.9" and command
`mvn clean install`
it is working fine locally and for our bitbucket pipeline. I read that this issue might be related to the combination of the JDK and surefire version used. Maybe this issue could be solved by using another JDK as part of your dockerfile by default?

As pointed out by you, upgrading to surefire version 3.0.0-M3 fixes the issue too.

pom.xml
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>3.0.0-M3</version>
</plugin>
```

which is fine for me!

Thanks,
Alex

**Comment by fwilhe** [comment] 2019-04-08 07:19
Hi Alex,

the MTA builder image uses Maven 3.6 which is not compatible with the older surefire version as far as I know. 

> Maybe this issue could be solved by using another JDK as part of your dockerfile by default?

We use openjdk 8 which should still be the most compatible version as of now.

I'm glad the issue is resolved for you, and I don't see anything we can do in the image, so I'm closing the issue.

Best regards

Florian

**Closed by fwilhe** 2019-04-08 07:19 UTC
